'use strict';
const $ = id => document.getElementById(id);
const storageKey = 'aether-v1';
const defaultDate = new Date(new Date().getFullYear() + 1, 0, 1).getTime();
let state = { name: '下一个重要时刻', target: defaultDate, tasks: [] };
try { const saved = JSON.parse(localStorage.getItem(storageKey)); if (saved && typeof saved.name === 'string' && Number.isFinite(saved.target) && Array.isArray(saved.tasks)) state = { name: saved.name, target: saved.target, tasks: saved.tasks.filter(t => typeof t.id === 'string' && typeof t.text === 'string') }; } catch {}
function save() { try { localStorage.setItem(storageKey, JSON.stringify(state)); } catch { $('announcement').textContent = '浏览器无法保存，当前设置仅在本次打开期间有效。'; } }
function updateDateLabel() { $('event-name').textContent = state.name; $('target-label').textContent = new Date(state.target).toLocaleString('sv-SE', {year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).replaceAll('-', ' . '); }
function tick() { let diff = Math.max(0, Math.floor((state.target - Date.now()) / 1000)); const values = [Math.floor(diff / 86400), Math.floor(diff / 3600) % 24, Math.floor(diff / 60) % 60, diff % 60]; ['days','hours','minutes','seconds'].forEach((id,i) => { const value = String(values[i]).padStart(i === 0 ? 3 : 2,'0'); if ($(id).textContent !== value) { $(id).textContent = value; $(id).classList.remove('change'); void $(id).offsetWidth; $(id).classList.add('change'); } }); $('status').textContent = state.target <= Date.now() ? '此刻，已经抵达' : '未来，正在靠近'; }
$('edit-date').onclick = () => { $('event-input').value = state.name; const d = new Date(state.target); $('date-input').value = new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0,16); $('date-dialog').showModal(); };
$('date-form').onsubmit = e => { e.preventDefault(); const target = new Date($('date-input').value).getTime(); if (!Number.isFinite(target) || !$('event-input').value.trim()) return; state.name = $('event-input').value.trim(); state.target = target; save(); updateDateLabel(); tick(); $('date-dialog').close(); };
document.querySelectorAll('[data-close]').forEach(b => b.onclick = () => $(b.dataset.close).close());
document.querySelectorAll('dialog').forEach(d => d.addEventListener('click',e => { if(e.target === d) { const r = d.getBoundingClientRect(); if(e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) d.close(); } }));
$('open-tasks').onclick = () => $('task-dialog').showModal();
function renderTasks() { $('task-list').replaceChildren(); $('task-count').textContent = state.tasks.length; $('empty-tasks').hidden = state.tasks.length > 0; state.tasks.forEach(task => { const li = document.createElement('li'); const button = document.createElement('button'); button.className = 'complete'; button.textContent = '✓'; button.setAttribute('aria-label', `完成：${task.text}`); const text = document.createElement('span'); text.textContent = task.text; li.append(button,text); $('task-list').append(li); button.onclick = () => { button.disabled = true; const r = button.getBoundingClientRect(); burst(r.left+r.width/2,r.top+r.height/2); playEnergy(); state.tasks = state.tasks.filter(t => t.id !== task.id); save(); li.classList.add('completed'); $('announcement').textContent = `已完成：${task.text}`; setTimeout(renderTasks,450); }; }); }
$('task-form').onsubmit = e => { e.preventDefault(); const text = $('task-input').value.trim(); if (!text) return; state.tasks.push({id: crypto.randomUUID(),text}); save(); renderTasks(); $('task-input').value = ''; $('task-input').focus(); };
let soundEnabled = false, audioContext;
$('sound').onclick = async () => { soundEnabled = !soundEnabled; $('sound').setAttribute('aria-pressed',String(soundEnabled)); $('sound').setAttribute('aria-label',soundEnabled ? '关闭音效' : '开启音效'); $('sound-label').textContent = soundEnabled ? '声音开启' : '声音关闭'; if(soundEnabled) { try { audioContext ||= new (window.AudioContext || window.webkitAudioContext)(); await audioContext.resume(); playEnergy(); } catch { soundEnabled = false; $('sound').setAttribute('aria-pressed','false'); $('sound-label').textContent = '声音不可用'; } } };
function playEnergy() { if (!soundEnabled || !audioContext) return; const now = audioContext.currentTime; [110,165,220].forEach((f,i) => { const osc = audioContext.createOscillator(), gain = audioContext.createGain(), filter = audioContext.createBiquadFilter(); osc.type='sine'; osc.frequency.setValueAtTime(f*2,now+i*.06); osc.frequency.exponentialRampToValueAtTime(f*.45,now+.8); filter.type='lowpass'; filter.frequency.value=650; gain.gain.setValueAtTime(0,now); gain.gain.linearRampToValueAtTime(.045,now+.08+i*.025); gain.gain.exponentialRampToValueAtTime(.0001,now+1.2); osc.connect(filter).connect(gain).connect(audioContext.destination); osc.start(now); osc.stop(now+1.3); }); }
const canvas = $('space'), ctx = canvas.getContext('2d'); let width, height, cubes=[], bursts=[]; const reduced = matchMedia('(prefers-reduced-motion: reduce)');
function resize() { width=innerWidth; height=innerHeight; const dpr=Math.min(devicePixelRatio||1,2); canvas.width=width*dpr; canvas.height=height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); cubes=Array.from({length:width<700?12:22},(_,i)=>({x:Math.random()*width,y:Math.random()*height,s:12+Math.random()*35,a:Math.random()*Math.PI,v:.08+Math.random()*.14,phase:i*1.4})); }
function cube(x,y,s,a,alpha) { ctx.save(); ctx.translate(x,y); ctx.rotate(a); ctx.globalAlpha=alpha; ctx.shadowColor='rgba(107,164,206,.15)'; ctx.shadowBlur=s*.4; const g=ctx.createLinearGradient(-s,-s,s,s); g.addColorStop(0,'rgba(255,255,255,.88)');g.addColorStop(.5,'rgba(212,230,246,.7)');g.addColorStop(1,'rgba(139,182,214,.45)');ctx.fillStyle=g;ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(0,-s*.65);ctx.lineTo(s*.58,-s*.3);ctx.lineTo(s*.58,s*.38);ctx.lineTo(0,s*.7);ctx.lineTo(-s*.58,s*.35);ctx.lineTo(-s*.58,-s*.3);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-s*.58,-s*.3);ctx.lineTo(0,0);ctx.lineTo(s*.58,-s*.3);ctx.moveTo(0,0);ctx.lineTo(0,s*.7);ctx.stroke();ctx.restore(); }
function burst(x,y) { const start=performance.now(); bursts.push({x,y,start,parts:Array.from({length:32},()=>({angle:Math.random()*Math.PI*2,distance:45+Math.random()*180,s:4+Math.random()*16,spin:Math.random()*4}))}); // Modal dialogs are in the top layer, so use a temporary dialog-local canvas.
const overlay = document.createElement('canvas'); overlay.className='burst-overlay'; Object.assign(overlay.style,{position:'fixed',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'10'}); const r=$('task-dialog').getBoundingClientRect(); overlay.width=r.width*2;overlay.height=r.height*2; $('task-dialog').append(overlay); const c=overlay.getContext('2d'); c.scale(2,2); const particles=Array.from({length:24},()=>({angle:Math.random()*Math.PI*2,v:35+Math.random()*95,s:3+Math.random()*7})); function draw(t){const p=(t-start)/900;c.clearRect(0,0,r.width,r.height); if(p>=1){overlay.remove();return;}particles.forEach(q=>{const distance=p<.25?(1-p/.25)*25:(p-.25)*q.v*2;c.save();c.translate(x-r.left+Math.cos(q.angle)*distance,y-r.top+Math.sin(q.angle)*distance);c.rotate(p*3+q.angle);c.globalAlpha=(1-p)*.8;c.fillStyle='#a3c9e5';c.shadowBlur=8;c.shadowColor='#d0eaff';c.fillRect(-q.s/2,-q.s/2,q.s,q.s);c.restore();});requestAnimationFrame(draw)} if(!reduced.matches)requestAnimationFrame(draw);else overlay.remove(); }
let previous=performance.now();function frame(t){const dt=Math.min(32,t-previous);previous=t;ctx.clearRect(0,0,width,height);cubes.forEach(q=>{if(!reduced.matches){q.y-=q.v*dt/16;q.a+=.0008*dt/16;if(q.y<-60)q.y=height+60;}const middle=Math.abs(q.x-width/2)<width*.38&&Math.abs(q.y-height*.47)<height*.19;cube(q.x+Math.sin(t*.0002+q.phase)*10,q.y,q.s,q.a,middle?.12:.43);});bursts=bursts.filter(b=>t-b.start<1600);bursts.forEach(b=>{const p=(t-b.start)/1600; if(reduced.matches)return;b.parts.forEach(q=>{const d=p<.2?(1-p/.2)*65:(p-.2)*q.distance;cube(b.x+Math.cos(q.angle)*d,b.y+Math.sin(q.angle)*d,q.s*(1-p*.6),q.spin+p*3,(1-p)*.8);});ctx.beginPath();ctx.ellipse(b.x,b.y,Math.max(1,p*210),Math.max(1,p*75),0,0,Math.PI*2);ctx.strokeStyle=`rgba(140,185,215,${(1-p)*.35})`;ctx.stroke();});requestAnimationFrame(frame)}
addEventListener('resize',resize);resize();requestAnimationFrame(frame);updateDateLabel();tick();setInterval(tick,1000);renderTasks();
