import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence} from 'framer-motion';
import * as THREE from 'three';
import '@fontsource/orbitron/latin-400.css';
import '@fontsource/orbitron/latin-500.css';
import './style.css';
function useReducedMotion(){
  const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);media.addEventListener('change',update);update();return()=>media.removeEventListener('change',update);},[]);
  return reduced;
}
const KEY='aether-v1';
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s.name==='string'&&Number.isFinite(s.target)&&Array.isArray(s.tasks))return {...s,tasks:s.tasks.filter(t=>typeof t.id==='string'&&typeof t.text==='string')};}catch{}return {name:'下一个重要时刻',target:new Date(new Date().getFullYear()+1,0,1).getTime(),tasks:[]};}
function Universe({pulse}){const mount=useRef(null),effect=useRef(null);const reduce=useReducedMotion();useEffect(()=>{let renderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}const host=mount.current;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));host.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.z=12;const group=new THREE.Group();scene.add(group);const geometries=[],materials=[];function add(geo,mat,obj){geometries.push(geo);materials.push(mat);group.add(obj);return obj;}for(let i=0;i<3;i++){const g=new THREE.TorusGeometry(3.15+i*.32,.008,6,160),m=new THREE.MeshBasicMaterial({color:i===1?0x29779a:0x55e8ef,transparent:true,opacity:.084});const ring=add(g,m,new THREE.Mesh(g,m));ring.rotation.x=1.1+i*.15;ring.rotation.y=i*.35;ring.position.y=.3;}const points=new Float32Array(330*3);for(let i=0;i<points.length;i++)points[i]=(Math.random()-.5)*27;const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(points,3));const pm=new THREE.PointsMaterial({size:.024,color:0x76cddc,transparent:true,opacity:.45});const stars=add(pg,pm,new THREE.Points(pg,pm));const burstG=new THREE.BoxGeometry(.09,.09,.09),burstM=new THREE.MeshBasicMaterial({color:0x70ffff,transparent:true,opacity:0});geometries.push(burstG);materials.push(burstM);const fragments=Array.from({length:55},()=>{const m=new THREE.Mesh(burstG,burstM);scene.add(m);return {mesh:m,v:new THREE.Vector3((Math.random()-.5)*6,(Math.random()-.5)*5,(Math.random()-.5)*3)};});let start=-10000;effect.current=()=>{start=performance.now();};function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}resize();window.addEventListener('resize',resize);let id;function draw(t){if(!reduce){group.children.slice(0,3).forEach((r,i)=>{r.rotation.z=t*.00006*(i%2?-1:1);});stars.rotation.y=t*.000008;}const p=(t-start)/1400;burstM.opacity=p>=0&&p<1&&!reduce?1-p:0;fragments.forEach(({mesh,v})=>{mesh.position.copy(v).multiplyScalar(Math.max(0,p));mesh.rotation.set(p*3,p*4,p*2);});renderer.render(scene,camera);id=requestAnimationFrame(draw);}id=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(id);window.removeEventListener('resize',resize);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose();host.replaceChildren();effect.current=null;};},[reduce]);useEffect(()=>{if(pulse)effect.current?.();},[pulse]);return <div className="universe" ref={mount} aria-hidden="true"/>;}
function Corners(){return <><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/></>;}
function Radar(){return <div className="radar" aria-hidden="true"><div className="radar-ring"/><div className="radar-ring inner"/><div className="radar-cross"/><div className="radar-sweep"/><span className="radar-point"/><b>TIME<br/>LOCKED</b></div>;}
function DataTrace(){
  const reduce=useReducedMotion();
  const [samples,setSamples]=useState(()=>Array.from({length:22},(_,i)=>30+Math.sin(i*.9)*12));
  useEffect(()=>{if(reduce)return;const id=setInterval(()=>setSamples(values=>[...values.slice(1),12+Math.random()*36]),700);return()=>clearInterval(id);},[reduce]);
  const path=samples.map((v,i)=>`${i===0?'M':'L'}${(i*160/(samples.length-1)).toFixed(1)} ${v.toFixed(1)}`).join(' ');
  return <div className="data-trace" aria-hidden="true"><svg viewBox="0 0 160 60"><defs><linearGradient id="trace-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ffa55a" stopOpacity=".18"/><stop offset="100%" stopColor="#ffa55a" stopOpacity="0"/></linearGradient></defs><path className="trace-area" d={`${path} L160 60 L0 60 Z`}/><path d={path}/><circle cx="160" cy={samples.at(-1)} r="2"/></svg><span className="trace-label">SIMULATED SIGNAL / 模拟信号</span></div>;
}
function App(){const [state,setState]=useState(load),[now,setNow]=useState(Date.now()),[task,setTask]=useState(''),[sound,setSound]=useState(false),[pulse,setPulse]=useState(0),[notice,setNotice]=useState(''),[dateError,setDateError]=useState('');const dialog=useRef(),nameInput=useRef(),dateInput=useRef(),audio=useRef(),reduce=useReducedMotion();useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch{setNotice('浏览器无法保存，设置仅在本次打开期间有效。');}},[state]);const diff=Math.max(0,Math.floor((state.target-now)/1000)),vals=[Math.floor(diff/86400),Math.floor(diff/3600)%24,Math.floor(diff/60)%60,diff%60];function energy(force=false){if((!sound&&!force)||!audio.current)return;const c=audio.current,t=c.currentTime;[100,150,200].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(f*2,t);o.frequency.exponentialRampToValueAtTime(f*.45,t+.85);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.04,t+.07+i*.025);g.gain.exponentialRampToValueAtTime(.0001,t+1.1);o.connect(g).connect(c.destination);o.start(t);o.stop(t+1.2);});}async function toggleSound(){if(sound){setSound(false);return;}try{audio.current ||= new (window.AudioContext||window.webkitAudioContext)();await audio.current.resume();setSound(true);energy(true);}catch{setNotice('此浏览器暂不支持音效。');}}function openDate(){nameInput.current.value=state.name;const d=new Date(state.target);dateInput.current.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);setDateError('');dialog.current.showModal();}function submitDate(e){e.preventDefault();const target=new Date(dateInput.current.value).getTime(),name=nameInput.current.value.trim();if(!name||!Number.isFinite(target)){setDateError('请输入名称和有效日期。');return;}setState(s=>({...s,name,target}));dialog.current.close();}function complete(t){energy();setPulse(p=>p+1);setState(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}));setNotice(`已完成：${t.text}`);}
return <><Universe pulse={pulse}/><div className="hex-field" aria-hidden="true"/><div className="vignette" aria-hidden="true"/><div className="app-shell"><header className="flex items-center justify-between"><a href="./" className="brand"><span className="logo">◈</span><span>AETHER <small>临界 / TEMPORAL INTERFACE</small></span></a><div className="header-right flex items-center gap-7"><span className="online"><i/> SYSTEM ONLINE</span><button onClick={toggleSound} aria-pressed={sound} className="sound-button">◖)) <span>{sound?'音效开启':'音效关闭'}</span></button></div></header><div className="top-rule"><span>PERSONAL TIME OPERATING SYSTEM</span><span>PROTOCOL 02.0 / LOCAL</span></div>
<main><div className="section-heading"><span className="cyan-dot"/> TEMPORAL CORE <span className="line"/><span className="subtle">时间，正在流向你。</span></div><section className="core-grid"><aside className="telemetry"><div className="micro-title">01 / TARGET LOCK</div><Radar/><div className="telemetry-line"><span>信号状态</span><b>已同步</b></div><div className="telemetry-line"><span>时间基准</span><b>本地时区</b></div><div className="waveform" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${8+Math.sin(i*1.6+(reduce?0:Math.floor(now/1000)))*6+((i*7)%13)}px`,animationDelay:`${i*.08}s`}}/>)}</div><span className="tiny">SIGNAL / CONTINUOUS</span></aside>
<div className="core-stage"><div className="ring ring-a"/><div className="ring ring-b"/><div className="holo-depth"><motion.div className="holo-panel" initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.8}}><Corners/><div className="panel-head"><span>TIME / CONTINUUM</span><span className="live">◉ LIVE COUNTDOWN</span></div><div className="countdown" role="timer" aria-label="剩余时间">{vals.map((v,i)=><React.Fragment key={i}>{i>0&&<span className="colon" aria-hidden="true"><i/><i/></span>}<div className="time-block"><div className="digit-float" style={{animationDelay:`${i*-.8}s`}}><motion.span className="digit" data-value={String(v).padStart(i===0?3:2,'0')} key={v} initial={reduce?false:{opacity:.5,y:-5,filter:'blur(3px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} transition={{duration:.3}}>{String(v).padStart(i===0?3:2,'0')}</motion.span><span className="digit-reflection" aria-hidden="true">{String(v).padStart(i===0?3:2,'0')}</span></div><span className="unit">{['DAYS / 天','HOURS / 时','MINUTES / 分','SECONDS / 秒'][i]}</span></div></React.Fragment>)}</div><div className="panel-foot"><span>{diff===0?'此刻，已经抵达':'未来，正在靠近'}</span><span className="tick-marks">|||||||||||||||||||||||||||||</span><span>SYNC / 01</span></div><div className="scanline"/><div className="glass-refract" aria-hidden="true"/></motion.div></div><button className="target-button" onClick={openDate}><span className="target-name">{state.name}</span><span className="target-date">{new Date(state.target).toLocaleString('sv-SE',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})} <b>↗</b></span></button><div className="projection-floor"><i/><i/><i/></div></div>
<aside className="data-aside"><div className="micro-title">02 / TEMPORAL DATA</div><div className="large-data">{String(vals[0]).padStart(3,'0')}<small>天，抵达目标</small></div><DataTrace/><div className="telemetry-line"><span>时间流</span><b>持续运行</b></div><div className="data-lines" aria-hidden="true">T+ / 0001.024<br/>CH / AETHER.02<br/>LINK / ESTABLISHED</div></aside></section>
<section className="tasks-panel"><Corners/><div className="tasks-heading"><div><div className="micro-title">MISSION QUEUE / 待完成事项</div><h1>抵达之前<span>每完成一件事，都更靠近一点。</span></h1></div><span className="task-total">{String(state.tasks.length).padStart(2,'0')} <small>待完成</small></span></div><div className="task-layout"><form onSubmit={e=>{e.preventDefault();if(!task.trim())return;setState(s=>({...s,tasks:[...s.tasks,{id:crypto.randomUUID(),text:task.trim()}]}));setTask('');}} className="task-form"><label htmlFor="new-task">新增目标 / ADD OBJECTIVE</label><div className="input-row"><span className="terminal-prompt" aria-hidden="true">&gt;</span><input id="new-task" value={task} onChange={e=>setTask(e.target.value)} maxLength={100} placeholder="写下下一件想完成的事…" required/><button type="submit" aria-label="添加事项">＋</button></div><span className="task-help">点击事项前的菱形，完成并释放能量。</span></form><ul className="task-list"><AnimatePresence initial={false}>{state.tasks.map((t,i)=><motion.li key={t.id} layout initial={reduce?false:{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={reduce?{opacity:0}:{opacity:0,x:35,filter:'blur(8px)',scale:.96}} transition={{duration:.4}}><button className="complete" onClick={()=>complete(t)} aria-label={`完成：${t.text}`}><span>✓</span></button><span className="task-index">{String(i+1).padStart(2,'0')}</span><span className="task-text">{t.text}</span><span className="task-state">待完成</span></motion.li>)}</AnimatePresence>{state.tasks.length===0&&<li className="empty"><span>◇</span><div>任务轨道已清空<small>从左侧添加事项，让每一秒都有方向。</small></div></li>}</ul></div></section></main><footer><span><i className="cyan-dot"/> ALL SYSTEMS NOMINAL</span><span>让每一秒，都有意义。</span><span>AETHER / ∞ POSSIBILITIES</span></footer></div><dialog ref={dialog} className="date-dialog" onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.current.close();}}}><form onSubmit={submitDate}><div className="dialog-head"><span>设定重要时刻</span><button type="button" onClick={()=>dialog.current.close()} aria-label="关闭日期设置">×</button></div><label>时刻名称<input ref={nameInput} maxLength={40} required/></label><label>目标日期与时间<input type="datetime-local" ref={dateInput} required/></label><p>按当前设备本地时区计算，自动保存至此浏览器。</p>{dateError&&<p role="alert">{dateError}</p>}<button type="submit" className="save-date">确认目标 ↗</button></form></dialog><div role="status" className="sr-only">{notice}</div></>;}
createRoot(document.getElementById('root')).render(<App/>);
